- hosts: 
  - centos7

  pre_tasks:
  - shell: echo 'Start'
  
  #roles:
  #- java
  #- tomcat

  tasks:
  - shell: echo 'Running'
  
  - name: print to stdout
    command: "uname -a"
    register: hello

  - debug: msg="{{ hello.stdout }}"


  post_tasks:
  - \shell: echo 'Finish'
